version: "3"

services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongo-4.2-data:/data/db
    env_file:
      - mongo-4.2/service.env
      - ../.env/mongo-4.2.env
    ports:
      - 27017:27017
    networks:
      - devsvcnet

volumes:
  mongo-4.2-data:
    driver: local
