version: "3"

services:
  vault:
    image: vault:1.13.3
    volumes:
      - ./vault-1.13/config:/vault/config
      - vault-1.13-data:/vault/file
    entrypoint: vault server -dev -dev-kv-v1 -config=/vault/config/vault.json
    env_file:
      - vault-1.13/service.env
      - ../.env/vault-1.13.env
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
      - 8201:8201
    networks:
      - devsvcnet

volumes:
  vault-1.13-data:
    driver: local
