version: "3"

services:
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.12.1
    volumes:
      - ./kibana-8.12/config/:/usr/share/kibana/config:ro
    env_file:
      - kibana-8.12/service.env
      - ../.env/kibana-8.12.env
    ports:
      - 5601:5601
    networks:
      - devsvcnet
