version: "3"

services:
  postgres:
    image: postgres:15.3
    volumes:
      - postgres-15.3-data:/var/lib/postgresql
    env_file:
      - postgres-15.3/service.env
      - ../.env/postgres-15.3.env
    ports:
      - 5432:5432
    networks:
      - devsvcnet

volumes:
  postgres-15.3-data:
    driver: local
