version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    volumes:
      - rabbitmq-3.12-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    env_file:
      - rabbitmq-3.12/service.env
      - ../.env/rabbitmq-3.12.env
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - devsvcnet

volumes:
  rabbitmq-3.12-data:
    driver: local
