version: "3"

services:
  postgres:
    image: postgres:15.6
    volumes:
      - postgres-15.6-data:/var/lib/postgresql
    env_file:
      - postgres-15.6/service.env
      - ../.env/postgres-15.6.env
    ports:
      - 5432:5432
    networks:
      - devsvcnet

volumes:
  postgres-15.6-data:
    driver: local
