version: "3"

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres-16.2-data:/var/lib/postgresql
    env_file:
      - postgres-16.2/service.env
      - ../.env/postgres-16.2.env
    ports:
      - 5432:5432
    networks:
      - devsvcnet

volumes:
  postgres-16.2-data:
    driver: local
