version: "3"

services:
  redis:
    image: redis:7.2
    volumes:
      - redis-7.2-data:/data
    env_file:
      - redis-7.2/service.env
      - ../.env/redis-7.2.env
    ports:
      - 6379:6379
    networks:
      - devsvcnet

volumes:
  redis-7.2-data:
    driver: local
