version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqlserver-2022-data:/var/opt/mssql
    env_file:
      - sqlserver-2022/service.env
      - ../.env/sqlserver-2022.env
    ports:
      - 1433:1433
    networks:
      - devsvcnet

volumes:
  sqlserver-2022-data:
    driver: local
