version: "3"

services:
  eventstore:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    volumes:
      - eventstore-23.10-data:/var/lib/eventstore
    env_file:
      - eventstore-23.10/service.env
      - ../.env/eventstore-23.10.env
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      - devsvcnet

volumes:
  eventstore-23.10-data:
    driver: local
