version: "3"

services:
  eventstore5:
    image: eventstore/eventstore:release-5.0.11
    volumes:
      - eventstore-5.0-data:/var/lib/eventstore
    env_file:
      - eventstore-5.0/service.env
      - ../.env/eventstore-5.0.env
    ports:
      - 51113:1113
      - 52113:2113
    networks:
      - devsvcnet

volumes:
  eventstore-5.0-data:
    driver: local
